/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AEqComparison extends PComparison
{
    private PExpression _lexp_;
    private PExpression _rexpr_;

    public AEqComparison()
    {
    }

    public AEqComparison(
        PExpression _lexp_,
        PExpression _rexpr_)
    {
        setLexp(_lexp_);

        setRexpr(_rexpr_);

    }
    public Object clone()
    {
        return new AEqComparison(
            (PExpression) cloneNode(_lexp_),
            (PExpression) cloneNode(_rexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqComparison(this);
    }

    public PExpression getLexp()
    {
        return _lexp_;
    }

    public void setLexp(PExpression node)
    {
        if(_lexp_ != null)
        {
            _lexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lexp_ = node;
    }

    public PExpression getRexpr()
    {
        return _rexpr_;
    }

    public void setRexpr(PExpression node)
    {
        if(_rexpr_ != null)
        {
            _rexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rexpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lexp_)
            + toString(_rexpr_);
    }

    void removeChild(Node child)
    {
        if(_lexp_ == child)
        {
            _lexp_ = null;
            return;
        }

        if(_rexpr_ == child)
        {
            _rexpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lexp_ == oldChild)
        {
            setLexp((PExpression) newChild);
            return;
        }

        if(_rexpr_ == oldChild)
        {
            setRexpr((PExpression) newChild);
            return;
        }

    }
}
