/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AGoal extends PGoal
{
    private final LinkedList _goal1_ = new TypedLinkedList(new Goal1_Cast());

    public AGoal()
    {
    }

    public AGoal(
        List _goal1_)
    {
        {
            this._goal1_.clear();
            this._goal1_.addAll(_goal1_);
        }

    }
    public Object clone()
    {
        return new AGoal(
            cloneList(_goal1_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGoal(this);
    }

    public LinkedList getGoal1()
    {
        return _goal1_;
    }

    public void setGoal1(List list)
    {
        _goal1_.clear();
        _goal1_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_goal1_);
    }

    void removeChild(Node child)
    {
        if(_goal1_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _goal1_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Goal1_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PGoal1 node = (PGoal1) o;

            if((node.parent() != null) &&
                (node.parent() != AGoal.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AGoal.this))
            {
                node.parent(AGoal.this);
            }

            return node;
        }
    }
}
