/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDec extends Token
{
    public TDec()
    {
        super.setText("--");
    }

    public TDec(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDec(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDec(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDec text.");
    }
}
