/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TEqComp extends Token
{
    public TEqComp()
    {
        super.setText("==");
    }

    public TEqComp(int line, int pos)
    {
        super.setText("==");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEqComp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEqComp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEqComp text.");
    }
}
